site_name: Xtyle
site_url: https://hlop3z.github.io/xtyle/
repo_url: https://github.com/hlop3z/xtyle
copyright: Copyright © Hlop3z

nav:
  - Introduction: index.md
  - Preact: preact.md
  - Hooks: hooks.md
  - CSS: css.md
  - Events: on-events.md
  - Theme: theme.md
  - Slots: slots.md
  - Plugins:
      - Install: plugins/index.md
      - Init: plugins/init.md
      #- Actions: plugins/actions.md
      - Directives: plugins/directives.md
      - Models: plugins/models.md
      - Router: plugins/router.md
      - Globals: plugins/globals.md
      - Store: plugins/store.md
  - Tools:
      - API: tools/api.md
      - i18n: tools/i18n.md
      - Device: tools/device.md
      - Others: tools/others.md
  - Built-in Directives:
      - x-ref: directives/ref.md
      - x-value: directives/value.md
      - x-hover: directives/hover.md
      - x-scroll: directives/scroll.md
      - x-swipe: directives/swipe.md
      - x-ripple: directives/ripple.md
      - x-resize: directives/resize.md
      - x-click-outside: directives/click-outside.md
  - Control Flow:
      - x-for: control-flow/for.md
      - x-switch: control-flow/switch.md
      - x-show: control-flow/show.md
      - x-if: control-flow/if.md
      - x-live: control-flow/live.md
      - x-portal: control-flow/portal.md
      - x-fallback: control-flow/fallback.md

# Configurations
watch:
  - custom_theme

theme:
  custom_dir: custom_theme/
  name: material
  locale: en
  features:
    # - navigation.tabs
    # - navigation.sections
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.annotate
    - navigation.expand

  icon:
    logo: material/alien

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
